[workspace]
resolver = "3"
members = ["repo-manifest", "repo-tool"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
quick-xml = { version = "0.37.5", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
url = { version = "2", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.12"
main_error = "0.1"
